// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.SweetAlert")>]
[<assembly: AssemblyProductAttribute("Feliz.SweetAlert")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for sweetalert2")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
[<assembly: InternalsVisibleToAttribute("Feliz.SweetAlert.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.SweetAlert"
    let [<Literal>] AssemblyProduct = "Feliz.SweetAlert"
    let [<Literal>] AssemblyDescription = "Fable bindings written in the Feliz-style for sweetalert2"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Debug"
    let [<Literal>] InternalsVisibleTo = "Feliz.SweetAlert.Tests"
