// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.SweetAlert")>]
[<assembly: AssemblyProductAttribute("Feliz.SweetAlert")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for sweetalert2")>]
[<assembly: AssemblyVersionAttribute("1.2.0")>]
[<assembly: AssemblyFileVersionAttribute("1.2.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.SweetAlert.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.SweetAlert"
    let [<Literal>] AssemblyProduct = "Feliz.SweetAlert"
    let [<Literal>] AssemblyDescription = "Fable bindings written in the Feliz-style for sweetalert2"
    let [<Literal>] AssemblyVersion = "1.2.0"
    let [<Literal>] AssemblyFileVersion = "1.2.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.SweetAlert.Tests"
